1.
Write a k-nearest neighbor classifier for the general case of k > 1. Given are
• M data vectors each of length N, stored in an M × N NumPy array called P.
• The class labels for the vectors stored in a length M array of integers called L. In
particular, L[i] == c means the i-th vector in P is from class c.
• A length N query vector called q.
Solve this in following steps: (a) find the distance from q to each data vector, (b) find the
class labels of the k smallest distances, (c) form a histogram of these labels and find the most
common class label. To keep things simple, if there is a tie for the most commonly occuring
class, you may output any of these classes.

In [9]:
import numpy as np

def generate_knn_data(M=100, N=5, num_classes=3, seed=None):
    if seed is not None:
        np.random.seed(seed)
    
    # Generate M data vectors, each of length N
    P = np.random.randn(M, N)  # Random normal distribution
    
    # Generate M class labels from num_classes
    L = np.random.randint(0, num_classes, size=M)
    
    # Generate a query vector of length N
    q = np.random.randn(N)
    
    return P, L, q

# Generate the inputs to the problem
P, L, q = generate_knn_data(M=10,N=3)
print("P (data vectors):\n", P)
print("L (class labels):\n", L)
print("q (query vector):\n", q)

k=5

# Calculate the distance of every point in P to q
distances = np.sqrt(np.sum((P - q) ** 2, axis=1))

# Find the indices of the k-nearest points
k_smallest_indices = np.argpartition(distances, k)[:k]

# Convert indices to class-labels
k_nearest_labels = L[k_smallest_indices]

# Count occurrences of each class label (histogram)
label_counts = np.bincount(k_nearest_labels)

# Find the most common class label
most_common_label = np.argmax(label_counts)

print("Most common class label:", most_common_label)



P (data vectors):
 [[ 1.630609    0.60693363  0.76620909]
 [-0.54660526  0.41788525  1.48199203]
 [ 1.83973413 -1.41238897  0.11336548]
 [ 2.22696176 -0.42111146  1.40373537]
 [ 0.04803324 -2.7754424   1.04670023]
 [ 0.67424733 -2.358624   -0.07812678]
 [ 0.86981859 -0.27990221 -1.09080391]
 [-1.39513654  0.30338924 -1.49532762]
 [ 0.57037696 -0.67332181 -0.20094934]
 [ 0.62410526 -0.42519526 -2.53480481]]
L (class labels):
 [0 1 0 0 0 2 0 2 1 0]
q (query vector):
 [-0.31368675  1.47436607  1.28900465]
Most common class label: 0


2.
The symmetric matching test is an alternative to the ratio test, where two keypoints, i from
image I0 and j from I1, are said to match each other if
• keypoint i’s descriptor is closer to the descriptor for j than any other descriptor found
in image I0, AND
• keypoint j’s descriptor is closer to the descriptor for i than any other descriptor found
in image I1.
Suppose the M0 descriptors for image I0 are stored in an M0 × k NumPy array D0 and the
M1 descriptors for image I1 are stored in an M1 × k NumPy array D1. Write Python code to
find all symmetric matches, outputting the idex pairs (i, j), one per line. Do this with as few
for loops as possible.